#redis配置
redis:
  #  数据库索引
  database: 0
  #    服务器地址
  host: 127.0.0.1
  #    服务器连接端口
  port: 6379
  #    链接密码
  password: root
  #    链接池
  pool:
    #    最大连接数（负值表示没有限制）
    max-active: 8
    #      最大阻塞等待时间（负值表示没有限制）
    max-wait: 1
    #      最大空闲链接
    max-idle: 8
    #      最小空闲链接
    min-idle: 0
    #    链接超时时间（毫秒）
  timeout: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: YSF@123.com
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  thymeleaf:
    cache: false
    prefix: classpath:/templates/


auth-server: http://localhost:9090/auth

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: handleCilentId
      clientSecret: secret
      accessTokenUri: ${auth-server}/oauth/token
      userAuthorizationUri: ${auth-server}/oauth/authorize
    resource:
      userInfoUri: ${auth-server}/user

douban:
  url: http://top.baidu.com/buzz?b=341&fr=topindex